require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PrayerneedsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Prayerneed. As you add validations to Prayerneed, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PrayerneedsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all prayerneeds as @prayerneeds" do
      prayerneed = Prayerneed.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:prayerneeds)).to eq([prayerneed])
    end
  end

  describe "GET show" do
    it "assigns the requested prayerneed as @prayerneed" do
      prayerneed = Prayerneed.create! valid_attributes
      get :show, {:id => prayerneed.to_param}, valid_session
      expect(assigns(:prayerneed)).to eq(prayerneed)
    end
  end

  describe "GET new" do
    it "assigns a new prayerneed as @prayerneed" do
      get :new, {}, valid_session
      expect(assigns(:prayerneed)).to be_a_new(Prayerneed)
    end
  end

  describe "GET edit" do
    it "assigns the requested prayerneed as @prayerneed" do
      prayerneed = Prayerneed.create! valid_attributes
      get :edit, {:id => prayerneed.to_param}, valid_session
      expect(assigns(:prayerneed)).to eq(prayerneed)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Prayerneed" do
        expect {
          post :create, {:prayerneed => valid_attributes}, valid_session
        }.to change(Prayerneed, :count).by(1)
      end

      it "assigns a newly created prayerneed as @prayerneed" do
        post :create, {:prayerneed => valid_attributes}, valid_session
        expect(assigns(:prayerneed)).to be_a(Prayerneed)
        expect(assigns(:prayerneed)).to be_persisted
      end

      it "redirects to the created prayerneed" do
        post :create, {:prayerneed => valid_attributes}, valid_session
        expect(response).to redirect_to(Prayerneed.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved prayerneed as @prayerneed" do
        post :create, {:prayerneed => invalid_attributes}, valid_session
        expect(assigns(:prayerneed)).to be_a_new(Prayerneed)
      end

      it "re-renders the 'new' template" do
        post :create, {:prayerneed => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested prayerneed" do
        prayerneed = Prayerneed.create! valid_attributes
        put :update, {:id => prayerneed.to_param, :prayerneed => new_attributes}, valid_session
        prayerneed.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested prayerneed as @prayerneed" do
        prayerneed = Prayerneed.create! valid_attributes
        put :update, {:id => prayerneed.to_param, :prayerneed => valid_attributes}, valid_session
        expect(assigns(:prayerneed)).to eq(prayerneed)
      end

      it "redirects to the prayerneed" do
        prayerneed = Prayerneed.create! valid_attributes
        put :update, {:id => prayerneed.to_param, :prayerneed => valid_attributes}, valid_session
        expect(response).to redirect_to(prayerneed)
      end
    end

    describe "with invalid params" do
      it "assigns the prayerneed as @prayerneed" do
        prayerneed = Prayerneed.create! valid_attributes
        put :update, {:id => prayerneed.to_param, :prayerneed => invalid_attributes}, valid_session
        expect(assigns(:prayerneed)).to eq(prayerneed)
      end

      it "re-renders the 'edit' template" do
        prayerneed = Prayerneed.create! valid_attributes
        put :update, {:id => prayerneed.to_param, :prayerneed => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested prayerneed" do
      prayerneed = Prayerneed.create! valid_attributes
      expect {
        delete :destroy, {:id => prayerneed.to_param}, valid_session
      }.to change(Prayerneed, :count).by(-1)
    end

    it "redirects to the prayerneeds list" do
      prayerneed = Prayerneed.create! valid_attributes
      delete :destroy, {:id => prayerneed.to_param}, valid_session
      expect(response).to redirect_to(prayerneeds_url)
    end
  end

end
